export const SET_AUTH_DETAILS = 'SET_AUTH_DETAILS';
export const SET_PROFILE_DETAILS = 'SET_PROFILE_DETAILS';

export const SET_BUS_STOPS_LIST = 'SET_BUS_STOPS_LIST';
export const SET_ENABLE_LOCATION = 'SET_ENABLE_LOCATION';

export const SET_ROUTES_LIST = 'SET_ROUTES_LIST';
export const SET_SELECTED_ROUTE = 'SET_SELECTED_ROUTE';

export const SET_CURRENT_TAB = 'SET_CURRENT_TAB';

export const SET_CURRENT_LOCATION = 'SET_CURRENT_LOCATION';
export const SET_SELECTED_BUS_STOP = 'SET_SELECTED_BUS_STOP';